### ISSUE TITLE
[BUG] - hyperlinks zijn 'visited' na upgrade, ook voor links in content-header 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-link#99]
**Omschrijf het probleem**
Links krijgen nu de paarse kleur van 'visited' te zijn. Dit was voordien niet het geval. Bovendien is dit ook voor de links in de content-header, wat al helemaal niet de bedoeling kan zijn. 

**Hoe te reproduceren**
Links bezoeken en zien dat ze paars kleuren. 

**Gewenst gedrag**
Dat ze nooit 'visited' worden en altijd 'blauw' blijven. 

**Screenshots**
Before:
<img width="1680" alt="Screenshot 2021-01-22 at 08 52 54" src="https://user-images.githubusercontent.com/8820456/105462660-3db0ae80-5c8f-11eb-9e61-fb98f71878ba.png">

After:
<img width="1680" alt="Screenshot 2021-01-22 at 08 52 45" src="https://user-images.githubusercontent.com/8820456/105462714-515c1500-5c8f-11eb-880c-38c4928bd0d5.png">

**Omgeving (gelieve aan te vullen):**
 - Browser chrome, safari
 - Versie component 4.0.7

**Extra info**
Ik weet niet of het door vl-ui-link komt of iets anders, want voordien was de versie van de component 4.0.5. Maar deze is geupgrade samen met een hoop andere componenten, inclusief de vl-ui-core.

**Comment by coemans** [comment]
> Dit was voordien niet het geval. Bovendien is dit ook voor de links in de content-header, wat al helemaal niet de bedoeling kan zijn.

Klopt dat dit bij de vorige huisstijl niet het geval was, maar kan je verduidelijken waarom dit niet gewenst is en al helemaal niet de bedoeling zou zijn bij een content-header?

**Comment by kevcraey** [comment]
zelfde gedrag als op vlaanderen.be
